version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
before_build:
- cmd: dotnet restore "C:\projects\projectivy-api\AnticevicApi\AnticevicApi.sln"
build:
  project: AnticevicApi\AnticevicApi.sln
  publish_wap: true
  verbosity: normal
test: off
artifacts:
- path: AnticevicApi\src\AnticevicApi\bin\Debug\netcoreapp1.0
  name: ProjectIvy.Api
  type: WebDeployPackage
deploy:
- provider: Environment
  name: ZgHome
  on:
    branch: master
    ProjectIvy.Api.deploy_website: true
    ProjectIvy.Api.site_name: api2.anticevic.net